# This is a basic workflow to help you get started with Actions

name: CI_Scheduled

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '15 15 * * *' commented out 7/28/2024
    #- cron:  '*/15 * * * *'
    #- cron:  '30 5,17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
              python-version: '3.8.5'
              
      
      - name:  import requests 
        run: python -m pip install requests
        
      - name:  import pytz
        run: python -m pip install pytz
        
      - name:  upgrade certifi
        run: python -m pip install certifi==2022.6.15
                    
      - name: Run Tests and Publish results
        run:  python ExecuteAll.py
        
       
      - name: remove index, add chart, Interim commit
        run:  |
              git config --local user.email "libcarter@gmail.com"
              git config --local user.name "libcarter"
              git add -A
              git commit -m "final commit" -a
              
      - name: push
        run: git push
